site_name: pytest-deselect-if
site_description: A plugin to deselect pytests tests rather than using skipif
site_author: Jason Giancono

theme: readthedocs

repo_url: https://github.com/jasongi/pytest-deselect-if

pages:
- Home: index.md
